### ISSUE TITLE
not sure what to do?

### ISSUE THREAD

**Issue by BeckyGH** [Montana-Media-Arts/441-WebTech-Spring2022-Examples#1]
I'm not sure this is where I go for help but I'm struggling with trying to figure out how to get my images to show up randomly, they show but in the same spot each time. I've tried numerous things and can not figure it out....anyone have help?
 
//array for id's of pics
let blankIds = ["pic01", "pic02", "pic03", "pic04", "pic05", "pic06", "pic07", "pic08", "pic09", "pic10"];

let actualImages = ["images/clover.jpg", "images/flower.jpg","images/smile.jpg", "images/square.jpg", "images/submarine.jpg", "images/elk.jpg", "images/train.jpg", "images/cactus.jpg", "images/bullseye.jpg", "images/house.jpg" ];
let actualCards = new Array();
 function createBoard()
{

    var backImageDisplay = "images/back.jpg";

    for(let i = 0; i < blankIds.length; i++)
    { 
        document.getElementById(blankIds[i]).src = backImageDisplay;
    }
    cardRandom(); 
     
} 

 HERES WHERE I'M NOT SURE HOW TO GET RANDOM TO WORK.........
function cardRandom()
{
  
    let randomNumber = Math.floor(Math.random() * actualImages.length );

        for (let i = 0; i < actualImages.length; i ++)
                {
                    actualCards.push(actualImages[i]);
                }
                //console.log("testing!");
}

function flip(number)
{
    document.getElementById(blankIds[number]).src= actualCards[number];  
}

**Comment by michaelcassens** [comment]
Have you tried putting randomNumber in actualImages[] in the for loop instead of "i"?  In the cardRandom function.  

Hope this helps!

**Comment by BeckyGH** [comment]
Loops are my nemesis right now. Thank You for your help!  

function cardRandom()
{
        for (let i = 0; i < actualImages.length; i ++)
                {
                    let randomNumber = Math.floor(Math.random() * actualImages.length );
                   
                    if(randomNumber < 10)
                    {
                        actualCards.push(actualImages[randomNumber]);
                    }
              
                }

                console.log("f@c!!");
}
